# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: default

jobs:
- job: DeployJob
  displayName: 'Deploy to Local'
  
  steps:
  - checkout: self
  
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: '6.0.x'
      
  - script: dotnet restore
    displayName: 'Restore dependencies'
    
  - script: dotnet build --configuration Release
    displayName: 'Build project'
    
  - task: DotNetCoreCLI@2
    displayName: 'Publish project'
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
      
  - task: CopyFiles@2
    displayName: 'Copy files to artifact staging directory'
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)/AWSCognito/bin/Release/net6.0/publish'
      Contents: '**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/publish'
      
  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/publish'
      artifact: 'deploy'

  - script: |
      # Add your deployment script here
      # For example, start your application or deploy to IIS
      # You might need to customize this based on your specific deployment needs
      cd $(Build.ArtifactStagingDirectory)/publish
      dotnet AWSCognito.dll
    displayName: 'Run application locally'
