# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: default

jobs:
- job: DeployJob
  displayName: 'Deploy to Local'
  
  steps:
  - checkout: self
  
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: '6.0.x'
      
  - script: dotnet restore
    displayName: 'Restore dependencies'
    
  - script: dotnet build --configuration Release
    displayName: 'Build project'



  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'myWebsiteName'